### ISSUE TITLE
Error plugin. Host / Ошибка плагина на хосте

### ISSUE THREAD

**Issue by KrasavaX** [ZOTTCE/samp-cef#10]
hread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 98, kind: AddrInUse, message: "Address already in use" })', server/src/server.rs:30:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

**Comment by ZOTTCE** [comment]
> message: "Address already in use"
адрес `0.0.0.0:7779` занят у тебя чем-либо уже

**Comment by KrasavaX** [comment]
То есть это у хостинга проблема уже?


пн, 9 авг. 2021 г. в 17:19, Eva ***@***.***>:

**Comment by KrasavaX** [comment]
Возникла другая проблема, картинка не появляться на хостинге, а именно не работает .so. Что делать?

**Comment by Royzen2** [comment]
Плагин на хостинге не работает. На vds пишет что он отключен, хотя все установлено.
