### ISSUE TITLE
Compilation error...

### ISSUE THREAD

**Issue by Sergey21133** [ZOTTCE/samp-cef#12]
Hi, I'm trying to build a project, but errors are flying out:
![изображение_2021-08-12_235200](https://user-images.githubusercontent.com/88857970/129268110-65e07292-3bd3-49ca-a5c9-cc21217a0db5.png)

**Comment by ZOTTCE** [comment]
![image](https://user-images.githubusercontent.com/6724377/129271310-2f9ed580-d6ef-49ba-828f-92a4214c130f.png)

**Comment by Sergey21133** [comment]
And you can go into more detail? please
