### ISSUE TITLE
Проблема Cef. 

### ISSUE THREAD

**Issue by Royzen2** [ZOTTCE/samp-cef#13]
Если включить одно и тоже видео на одинаковых портах. То один из серверов просто не запуститься /выключится.
Можно решить это путем переписывания скрипта. Если в server.cfg создать port_cef и от туда получать значения порта. ( мой вариант) 
Надеюсь вы это заметите.

**Comment by Royzen2** [comment]
![IMG_20210813_014207](https://user-images.githubusercontent.com/64889727/129279215-16168873-86a7-4547-b4e0-30af60a9c385.jpg)

**Comment by zhepa** [comment]
о проблеме уже известно. разраб будет решать.
@ZOTTCE приступай
