### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by Rams25** [ZOTTCE/samp-cef#24]
Hi :)
SAMP-CEF isn't utf-8 in input text, how to set utf-8 charset please ?

Thanks you.

**Comment by ZOTTCE** [comment]
samp server doesn't use utf8
so you should recompile the server plugin [using](https://github.com/ZOTTCE/samp-cef/blob/a00e41512ea7ce97778e30ffcd05c486d552f8d0/server/src/lib.rs#L429) the encoding of your server (win1251, win1252, etc)
also, the client plugin currently [assumes](https://github.com/ZOTTCE/samp-cef/blob/a00e41512ea7ce97778e30ffcd05c486d552f8d0/client/src/app.rs#L557) that the client uses `win1251` encoding.

**Comment by Rams25** [comment]
Thanks you very much !

**Comment by JustinzDev** [comment]
> samp server doesn't use utf8 so you should recompile the server plugin [using](https://github.com/ZOTTCE/samp-cef/blob/a00e41512ea7ce97778e30ffcd05c486d552f8d0/server/src/lib.rs#L429) the encoding of your server (win1251, win1252, etc) also, the client plugin currently [assumes](https://github.com/ZOTTCE/samp-cef/blob/a00e41512ea7ce97778e30ffcd05c486d552f8d0/client/src/app.rs#L557) that the client uses `win1251` encoding.

but i want to use win874 and in samp-rs don't have WINDOWS_874 how to ?

**Comment by mafxgaaa** [comment]
CMD:twa(playerid, params[])
{
    cef_hide_browser(playerid, INTERFACE_AREATBOX_ID, false);
    cef_emit_event(playerid, "interface:Arertbox", CEFSTR(params));
    SendClientMessageEx(playerid, COLOR_RED, params);
    return 1;
}

cef.on("interface:Arertbox", (text) => {
            document.getElementById("Arertbox").innerText = `${text}`;
        });
        
        how to encode
