### ISSUE TITLE
problem cef_client.log

### ISSUE THREAD

**Issue by D13G00** [ZOTTCE/samp-cef#4]
`07:55:14 [TRACE] (1) client_api::gta::d9_proxy: [C:\Users\zottc\.cargo\git\checkouts\samp-client-api-db116afb27d404f1\7035074\src\gta\d9_proxy.rs:53] finding function and hooking ... (d9_proxy::set_proxy)
07:55:14 [TRACE] (1) client_api::gta::d9_proxy: [C:\Users\zottc\.cargo\git\checkouts\samp-client-api-db116afb27d404f1\7035074\src\gta\d9_proxy.rs:55] done enable it ... (d9_proxy::set_proxy)
07:55:14 [TRACE] (1) client_api::gta::d9_proxy: [C:\Users\zottc\.cargo\git\checkouts\samp-client-api-db116afb27d404f1\7035074\src\gta\d9_proxy.rs:64] done ... (d9_proxy::set_proxy)
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:250] app::initialize()
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:251] App::new() ->
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:117] App::new()
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:121] Audio::new()
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:125] Manager::new()
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:129] crate::external::initialize
07:55:14 [TRACE] (2) client::app: [client\src\app.rs:256] CEF: crate::render::initalize()
07:55:14 [TRACE] (2) client::render: [client\src\render.rs:69] hooking CEntity::render
07:55:14 [TRACE] (2) client::render: [client\src\render.rs:79] hooking ok ...
07:55:14 [TRACE] (3) client::rodio_audio: [client\src\rodio_audio.rs:178] audio_thread start
07:55:17 [TRACE] (5) client: [client\src\lib.rs:61] DllMain reason == DLL_PROCESS_DETACH calling unitialize
07:55:17 [TRACE] (5) client::app: [client\src\app.rs:279] app::uninitialize()
07:55:17 [TRACE] (5) client::app: [client\src\app.rs:282] app::uninitialize call once ->
07:55:17 [TRACE] (5) client::app: [client\src\app.rs:100] App::drop
07:55:17 [TRACE] (5) client::browser::manager: [client\src\browser\manager.rs:549] manager::shutdown_cef() cef_running: false
07:55:17 [TRACE] (5) client::app: [client\src\app.rs:290] app::quit()`

is this normal?

**Comment by SatoruMikami** [comment]
> `07:55:14 [TRACE] (1) client_api::gta::d9_proxy: [C:\Users\zottc\.cargo\git\checkouts\samp-client-api-db116afb27d404f1\7035074\src\gta\d9_proxy.rs:53] finding function and hooking ... (d9_proxy::set_proxy) 07:55:14 [TRACE] (1) client_api::gta::d9_proxy: [C:\Users\zottc\.cargo\git\checkouts\samp-client-api-db116afb27d404f1\7035074\src\gta\d9_proxy.rs:55] done enable it ... (d9_proxy::set_proxy) 07:55:14 [TRACE] (1) client_api::gta::d9_proxy: [C:\Users\zottc\.cargo\git\checkouts\samp-client-api-db116afb27d404f1\7035074\src\gta\d9_proxy.rs:64] done ... (d9_proxy::set_proxy) 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:250] app::initialize() 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:251] App::new() -> 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:117] App::new() 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:121] Audio::new() 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:125] Manager::new() 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:129] crate::external::initialize 07:55:14 [TRACE] (2) client::app: [client\src\app.rs:256] CEF: crate::render::initalize() 07:55:14 [TRACE] (2) client::render: [client\src\render.rs:69] hooking CEntity::render 07:55:14 [TRACE] (2) client::render: [client\src\render.rs:79] hooking ok ... 07:55:14 [TRACE] (3) client::rodio_audio: [client\src\rodio_audio.rs:178] audio_thread start 07:55:17 [TRACE] (5) client: [client\src\lib.rs:61] DllMain reason == DLL_PROCESS_DETACH calling unitialize 07:55:17 [TRACE] (5) client::app: [client\src\app.rs:279] app::uninitialize() 07:55:17 [TRACE] (5) client::app: [client\src\app.rs:282] app::uninitialize call once -> 07:55:17 [TRACE] (5) client::app: [client\src\app.rs:100] App::drop 07:55:17 [TRACE] (5) client::browser::manager: [client\src\browser\manager.rs:549] manager::shutdown_cef() cef_running: false 07:55:17 [TRACE] (5) client::app: [client\src\app.rs:290] app::quit()`
> 
> is this normal?

Yes
