### ISSUE TITLE
No CEF_PATH env variable.

### ISSUE THREAD

**Issue by nexquery** [ZOTTCE/samp-cef#5]
I am getting the following error even though I have specified the CEF_PATH path. How can I solve this problem?

Indicated path:
[https://i.imgur.com/Bouuz4l.jpg](https://i.imgur.com/Bouuz4l.jpg)
[https://i.imgur.com/lsRaRkC.jpg](https://i.imgur.com/lsRaRkC.jpg)

Error received:
[https://i.imgur.com/EKQHgTn.jpg](https://i.imgur.com/EKQHgTn.jpg)

**Comment by ZOTTCE** [comment]
It looks like you run `cargo` commands from `cmd.exe` and maybe you set this variable from `powershell.exe`. You cannot mix different shells. It should work as expected if you do it right.

**Comment by nexquery** [comment]
Thanks for your answer.  How can I update this plugin to version 0.3 DL?

**Comment by ZOTTCE** [comment]
To make it work on 0.3DL someone should find addresses and structures and extend [this crate](https://github.com/ZOTTCE/samp-client-api) with them.

**Comment by nexquery** [comment]
Is there a tutorial for finding addresses?  If so, I would like to contribute.

**Comment by ZOTTCE** [comment]
I guess [s0beit](https://github.com/BlastHackNet/mod_s0beit_sa-1/tree/samp-dl) has this.

**Comment by nexquery** [comment]
If I can compile the plugin, I will work on the addresses, but I could not compile it. I am getting the following errors while compiling. Can you help with this?

[https://i.imgur.com/MHbr9gS.jpeg](https://i.imgur.com/MHbr9gS.jpeg)

**Comment by ZOTTCE** [comment]
Remove `libcef.lib` from `CEF_PATH`. That should contain the directory name only

**Comment by nexquery** [comment]
I have successfully completed the compilation process. For 0.3DL would it be enough for me to update the addresses here?
[Address](https://github.com/ZOTTCE/samp-client-api/blob/c9ffefb195fa7fc4277250c2fa4faf57def63a0c/src/samp/v037r3.rs#L9)

**Comment by ZOTTCE** [comment]
Nope, all addresses should be changed. Also, as I know there is a difference between structures.

**Comment by nexquery** [comment]
I guess I need to do a lot of research on addresses. Thank you for your help.
