### ISSUE TITLE
Connecting to CEF from Pawn

### ISSUE THREAD

**Issue by VITEBSKY** [ZOTTCE/samp-cef#8]
Hello. Can you please explain in more detail how I can call CEF from Pawn. I know there are examples, but I don't understand a little. If you have a PWN file, can you send it to me?

**Comment by VITEBSKY** [comment]
Также нужно ли загружать файлы интерфейса прямо на сайт?

**Comment by VITEBSKY** [comment]
Also, do you need to upload interface files directly to the site?

**Comment by ZOTTCE** [comment]
> 
> 
> Hello. Can you please explain in more detail how I can call CEF from Pawn. I know there are examples, but I don't understand a little. If you have a PWN file, can you send it to me?

You should create a browser from your game mode. Then you can access it using an event system. I guess you can find examples for [ragemp](https://rage.mp) and [fivem](https://fivem.net). This plugin has quite a similar API and idea.

> 
> 
> Also, do you need to upload interface files directly to the site?

Yes, your files should be hosted somewhere on the net.

**Comment by zhepa** [comment]
@ZOTTCE привет хочу сделать телек в тачку (навигатор) как в Вашем примере столкнулся с проблемой: машину создаю все ок работаю но когда пытаюсь подключить телек в onplayerupdate телек не постоянно черный и звук рябит

**Comment by VITEBSKY** [comment]
@ZOTTCE It seems like I'm doing everything right, I still can't interact with the browser. Perhaps this is the error - https://imgur.com/a/BxdmY7x?

By the way. After logging out from the server, this is the error - https://imgur.com/a/clzshDo. Does it play a role?

I also wanted to know if there will be problems with the plugin when there are 200 people on the server?

**Comment by VITEBSKY** [comment]
Can I host files on a local hosting site?

**Comment by VITEBSKY** [comment]
@zhepa Можно связаться с тобой, если ты разобрался с интерфейсами?

**Comment by Rams25** [comment]
> Can I host files on a local hosting site?

No u can't, but u can host files from github repo and drop html view
